# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9c873110d68e0394ef48aa629be8290bbe26676fa09e4c6653ba5a1faaa54f57188c9b99768934e22e0e3b9a3ace81af47ccbc560e7218b37b487b006157e2a

test:
  secret_key_base: 2d2bece767cdd9f9d2b0e1d57db3baa1186c95f2ca1400740d9c9055d595688b0792d28a16cf6587a8fafb9a8e804237a22085d778f7d20963b80a2cddff44bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
